name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: The version of Minecraft you are using
      placeholder: e.g. 1.20.1
    validations:
      required: true

  - type: input
    id: mod-loader
    attributes:
      label: Mod Loader
      description: The mod loader you are using (Forge or Fabric)
      placeholder: e.g. Forge
    validations:
      required: true

  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: The version of the mod you are using
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
